name: Windows Server 2019 (VSC)
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Setup VSCode Server session
        uses: NyaMisty/vscode-server-action@main
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          #machineName: myMachine # optional, default: GitHub workflow run ID
          timeout: '3600000' # 1 hour